version: '3.8'

services:
  blue-whatsapp-bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      # ASP.NET Core Configuration
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      
      # WhatsApp Cloud API Configuration
      # IMPORTANT: Replace these values with your actual WhatsApp credentials
      # Or use .env file (recommended for production)
      - WhatsAppCloud__AccessToken=${WHATSAPP_ACCESS_TOKEN:-YOUR_WHATSAPP_ACCESS_TOKEN_HERE}
      - WhatsAppCloud__PhoneNumberId=${WHATSAPP_PHONE_NUMBER_ID:-YOUR_PHONE_NUMBER_ID_HERE}
      - WhatsAppCloud__BaseEndpoint=https://graph.facebook.com/v22.0
      - WhatsAppCloud__ApiVersion=v22.0
      - WhatsAppCloud__TimeoutSeconds=30
      - WhatsAppCloud__EnableLogging=true
      
      # Database Configuration (SQLite is used by default)
      # The database file will be persisted in the volume
      
    volumes:
      # Persist SQLite database
      - ./data:/app/data
      - whatsapp-db:/app/data
    
    restart: unless-stopped
    
    # Health check to ensure the service is running
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  whatsapp-db:
    driver: local

# Example of how to override configuration with .env file
# Create a .env file in the same directory with:
# WHATSAPP_ACCESS_TOKEN=your_actual_token
# WHATSAPP_PHONE_NUMBER_ID=your_actual_phone_id